config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get 'tasks', to: 'tasks#index', as: :tasks #read
post 'tasks', to: 'tasks#create' #create
get 'tasks/new', to: 'tasks#new', as: :new_task
#create
get 'tasks/:id/edit', to: 'tasks#edit' , as: :edit_task #update
get 'tasks/:id', to: 'tasks#show', as: :task #read
patch 'tasks/:id', to: 'tasks#update'#update
delete 'tasks/:id', to: 'tasks#destroy'#delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params).save
    redirect_to tasks_path
  end
  
  def edit
    @task= Task.find(params[:id])
  end

  def update
     @task= Task.find(params[:id])
     @task.update(task_params)
     redirect_to task_path(@task)
  end

  def destroy
      @task= Task.find(params[:id])
      @task.destroy
      redirect_to tasks_path
  end
  private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
   <%= f.label :title, "title "%>
  <%= f.text_field :title %>
   <%= f.label :details, "Details "%>
  <%= f.text_field :details %>
   <%= f.label :completed, "Completed "%>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
<%= link_to "back to tasks", tasks_path %>

app/views/tasks/index.html.erb
<h1>To do list!</h1>


<% @tasks.each do |task| %>

<h2> <%= "(X)" if task.completed %> <%= link_to task.title, task_path(task.id) %></h2>	

<%=link_to "More Details", task_path(task)  %>


  ...
<% end %>
<%=link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
   <%= f.label :title, "title "%>
  <%= f.text_field :title %>
   <%= f.label :details, "Details "%>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>
<%= @task.details %>
<%= @task.completed ? "This task is done": "this task is pending" %>
<%=link_to "edit", edit_task_path  %>
<%= link_to "back to tasks", tasks_path %>
<%= link_to task_path(@task), method: :delete, data: {confirm: "Are you sure?"} do %> <i class="fas fa-trash"></i> <% end %>